version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: myNewSql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_ROOT_PASSWORD: Qwerty_12345
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloakNew
    command: start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL:
        jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: Qwerty_12345
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9091:8080"
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data: